name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Compile .java
        run: |
          find src -name "*.java" > sources.txt || true
          javac -d bin @sources.txt
      - name: Run HelloWorld
        run: |
          java -cp bin HelloWorld || true

  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Run build script
        run: |
          powershell -NoProfile -ExecutionPolicy Bypass -Command .\scripts\build_all.ps1
